[package]
name = "rotor"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.22"
uefi = { version = "0.33.0", features = ["logger", "panic_handler"] }

[build-dependencies]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
